### ISSUE TITLE
LICENSE file missing from latest release

### ISSUE THREAD

**Issue by johnthagen** [zopefoundation/zope.event#13]
Tools such as [`pip-licenses`](https://github.com/raimon49/pip-licenses) use the LICENSE file included in uploaded Python packages to generate license reports. The latest release of `zope.event` does not have a LICENSE file included.

Could a new release of `zope.event` be released using the latest `wheel` library that pulls in the LICENSE file automatically?

**Comment by jamadden** [comment]
zope.event 4.5.0 contains this file in the wheel.

Note that this file has always been in the sdist, and the `License` classifier part of the metadata, exposed in both sdists and wheels.

**Comment by johnthagen** [comment]
Thanks!
