### ISSUE TITLE
Documentation - Sync vs. Async

### ISSUE THREAD

**Issue by asaf-kali** [zopefoundation/zope.event#15]
Hey,
If I'm not mistaken, the basic event system is synchronous (meaning that after `dispatch`, the process will wait until all subscribers have processed the event). This may be worth mentioning in the README and documentation.

**Comment by mgedmin** [comment]
That sounds reasonable.  Would you care to prepare a PR?

**Comment by asaf-kali** [comment]
Will do

**Comment by icemac** [comment]
@asaf-kali This issue is fixed by #16, right?

**Comment by asaf-kali** [comment]
It does.
