### ISSUE TITLE
Deprecated setuptools parameter

### ISSUE THREAD

**Issue by BurstingBrain** [zopefoundation/zope.event#25]
### What I did:

I installed this package on gentoo

### What I expect to happen:

Just that the package would install without anything specific

### What actually happened:

I got a QA warning saying the following: 

 * Messages for package dev-python/zope-event-5.0:
 * Log file: /var/log/portage/build/dev-python/zope-event-5.0:20240503-195705.log

 * QA Notice: setuptools warnings detected:
 * 
 *      The namespace_packages parameter is deprecated.

### What version of Python and Zope/Addons I am using:
I was on python3.11 and python3.12 on Gentoo and compiling from sources.

**Comment by icemac** [comment]
Thank you for your report. This problem is tracked in https://github.com/zopefoundation/meta/issues/194 and has to be solved for all 117 packages of the `zope` namespace at once.

**Comment by BurstingBrain** [comment]
oh ok I wasn't aware. Thanks for the kind response
